#!/usr/bin/env python3
"""
stub_morning.py — Generate a placeholder morning brief when the main cron fails.

Used by the 6:00 AM ET backstop cron (id 34e3fde2) when today's per-date
commentary/YYYY-MM-DD/index.html is missing. Writes a stub that:

- Lays out the standard sections (Overnight Headlines, Pre-Market Futures,
  Calendar, What to Watch, Structural Read) with placeholder bullets
- Title says "morning brief not generated yet — check back after 6:30 AM ET"
- Is ALWAYS overwritten by the main cron's later runs
- Includes a meta note in the article explaining the stub status

Idempotent: skips if today's per-date page already exists with content.
"""

import os
import re
import shutil
from datetime import date, datetime
from pathlib import Path
import pytz

ROOT = Path(__file__).resolve().parent.parent
WEBSITE_DIR = ROOT / "website"
COMMENTARY_DIR = WEBSITE_DIR / "commentary"

ET = pytz.timezone("America/New_York")


def today_iso() -> str:
    return datetime.now(ET).strftime("%Y-%m-%d")


def human_date(iso: str) -> str:
    y, m, d = iso.split("-")
    dt = date(int(y), int(m), int(d))
    return dt.strftime("%A, %B %-d, %Y")


def generate_stub(iso: str) -> Path:
    target_dir = COMMENTARY_DIR / iso
    target = target_dir / "index.html"
    target_dir.mkdir(parents=True, exist_ok=True)

    if target.exists() and target.stat().st_size > 0:
        return target  # idempotent

    human = human_date(iso)

    # Title format (anti-pattern #125): the document <title> and visible H2 must
    # match. Stubs don't have a real one-liner, so we use a descriptive placeholder.
    doc_title = f"Morning Brief — {human} | Dependability"
    stub_h2 = f"{human} Morning Brief — Pending Canonical Publish"

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
 <meta charset="UTF-8">
 <meta name="viewport" content="width=device-width, initial-scale=1.0">
 <title>{doc_title}</title>
 <meta name="description" content="[STUB] Morning brief for {iso} not yet generated by the main cron. The 6:00 AM ET backstop placeholder will be replaced when the canonical brief ships.">
 <link rel="canonical" href="https://dependability.us/commentary/{iso}/">
 <meta property="og:title" content="{doc_title}">
 <meta property="og:description" content="[STUB] Morning brief for {iso} not yet generated by the main cron. The 6:00 AM ET backstop placeholder will be replaced when the canonical brief ships.">
 <link rel="icon" type="image/svg+xml" href="/favicon.svg">
 <link rel="stylesheet" href="/style.css">
</head>
<body>

<div id="site-utility"></div>
<div id="site-nav"></div>

<main>

<div class="page-content">
<nav class="article-breadcrumb" aria-label="Breadcrumb">
  <a href="/">Home</a><span class="sep">›</span>
  <a href="/commentary/">Commentary</a><span class="sep">›</span>
  <span aria-current="page">{iso}</span>
</nav>

<div style="background:#fff3cd;border:1px solid #ffe69c;padding:24px;margin:24px 0;border-radius:6px;">
 <p style="margin:0;color:#7a5d00;font-weight:600;">⚠️ Stub brief — main cron did not produce today's analysis.</p>
 <p style="margin:8px 0 0;color:#7a5d00;">This placeholder was generated by the 6:00 AM ET backstop because the main 5:55 AM morning cron's LLM step failed. It will be replaced automatically when the canonical brief ships.</p>
 <p style="margin:8px 0 0;color:#7a5d00;font-size:.9rem;">Generated: {datetime.now(ET).strftime("%Y-%m-%d %H:%M:%S %Z")}</p>
</div>

<div style="background:#fff;border:1px solid #e0e0e0;padding:24px;margin-bottom:28px;">
 <div class="category-label" style="margin-bottom:14px;text-align:center;">MORNING BRIEF — PLACEHOLDER</div>
 <h2 style="margin-bottom:16px;border-bottom:2px solid #c8001e;padding-bottom:8px;text-align:center;">{stub_h2}</h2>

 <div class="article-body">

<p>The Dependability morning brief for {human} has not yet been published. The canonical pre-market analysis runs at 5:55 AM ET; this placeholder was created by the 6:00 AM ET backstop because the main cron did not produce today's brief on schedule.</p>

<h2>Overnight Headlines</h2>
<p><em>Pending — check back after 6:30 AM ET for the canonical analysis.</em></p>

<h2>Pre-Market Futures</h2>
<ul>
  <li><strong>S&amp;P 500 futures (ES):</strong> pending</li>
  <li><strong>Nasdaq futures (NQ):</strong> pending</li>
  <li><strong>10-year yield:</strong> pending</li>
</ul>

<h2>Calendar — {human}</h2>
<p><em>Pending.</em></p>

<h2>What to Watch at the Open</h2>
<ol>
  <li><em>Pending.</em></li>
</ol>

<h2>The Structural Read</h2>
<p><em>Pending.</em></p>

<p style="margin-top:32px;color:#888;font-size:.9rem;"><strong>About this stub:</strong> generated by the 6:00 AM ET morning-brief backstop (cron id <code>34e3fde2-e465-488e-adc4-6cc0224bdc92</code>). This page will be replaced by the canonical brief when the main cron succeeds.</p>

</div>
</div>

<div style="text-align:center;margin:32px 0 8px;">
 <a href="/commentary/archive/" style="font-size:.95rem;color:#c8001e;text-decoration:none;border-bottom:1px solid #c8001e;">View all morning analyses →</a>
</div>

</div>

<section class="eeat-block" aria-label="About this article">
 <h2>About this stub</h2>
 <p>This is a placeholder page generated automatically because the 5:55 AM ET main morning-brief cron did not produce a canonical brief for {iso}. The placeholder exists so that <code>/commentary/</code> always shows today's date as the most recent analysis, rather than silently displaying yesterday's brief as if it were today. The page will be overwritten by the canonical brief when the main cron completes successfully.</p>
</section>

</main>

<div id="site-footer"></div>
<script src="/nav.js"></script>
<script src="/footer.js"></script>

</body>
</html>
"""
    tmp = target.with_suffix(".html.tmp")
    tmp.write_text(html)
    os.replace(tmp, target)
    return target


def main():
    iso = today_iso()
    target = generate_stub(iso)
    print(f"Generated stub: {target} ({target.stat().st_size} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
